pipeline_template: docker/Jenkinsfile-1
email_reply_to: no-reply@salesforce.com
compliance_required: false
docker_test_images:
    - sfci/docker-images/sfdc_rhel9_java_build
unit_tests_command: echo "Success"
production_branch: main
promote_to_falcon: true
