pipeline_template: docker/Jenkinsfile-1
email_reply_to: ast-notifications@salesforce.com     # Change this to your group's e-mail address!
time_out_mins: 180                                  # (Optional default = 180
compliance_required: false                           # (Optional) default = true
docker_test_images: # The image(s) that will be used to run your unit tests (Unit tests will be run against each image)
    - sfci/docker-images/sfdc_centos7_java11_build:75
unit_tests_command: mvn -V -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn --batch-mode verify                      # The command we'll run for the unit tests stage
production_branch: master # (Optional) default = master (master branch of github repo)
promote_to_falcon: true
